\hypertarget{classnumpy_1_1testing_1_1__private_1_1utils_1_1KnownFailureException}{}\doxysection{numpy.\+testing.\+\_\+private.\+utils.\+Known\+Failure\+Exception Class Reference}
\label{classnumpy_1_1testing_1_1__private_1_1utils_1_1KnownFailureException}\index{numpy.testing.\_private.utils.KnownFailureException@{numpy.testing.\_private.utils.KnownFailureException}}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Raise this exception to mark a test as a known failing test.\end{DoxyVerb}
 Inheritance diagram for numpy.\+testing.\+\_\+private.\+utils.\+Known\+Failure\+Exception\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{classnumpy_1_1testing_1_1__private_1_1utils_1_1KnownFailureException}
\end{center}
\end{figure}


The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/\+Lib/site-\/packages/numpy/testing/\+\_\+private/utils.\+py\end{DoxyCompactItemize}
